// Mock data for Olive frontend
// Replace with real API calls when backend is connected

export const mockUser = {
  id: 'u1',
  name: 'Sarah Johnson',
  username: 'sarahj',
  email: 'sarah@example.com',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
  bio: 'Love hiking, photography and meeting new people 🌿',
  location: 'San Francisco, CA',
  skills: ['Photography', 'Hiking', 'Yoga'],
  interests: ['Nature', 'Art', 'Music', 'Cooking'],
  joinedDate: '2024-01-15',
  activitiesJoined: 12,
  activitiesCreated: 3,
  connections: 48,
};

export const mockActivities = [
  {
    id: 'a1',
    title: 'Guitar Jam Session',
    category: 'Music',
    date: 'Today, 6:00 PM',
    location: 'Downtown Music Hub',
    city: 'San Francisco',
    attendees: 12,
    capacity: 20,
    image: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=400&q=80',
    host: { name: 'Alex Morgan', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex' },
    tags: ['Music', 'Guitar', 'Beginner Friendly'],
    description: 'Join us for a relaxed guitar jam session! All skill levels welcome. Bring your guitar and lets make some music together.',
    isJoined: true,
    isFree: true,
    points: 10,
  },
  {
    id: 'a2',
    title: 'Nature Walk',
    category: 'Outdoors',
    date: 'Sep 2 · 7:00 AM',
    location: 'Golden Gate Park',
    city: 'San Francisco',
    attendees: 20,
    capacity: 30,
    image: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=400&q=80',
    host: { name: 'James Lee', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James' },
    tags: ['Outdoors', 'Nature', 'Fitness'],
    description: 'A refreshing morning walk through beautiful trails. Perfect for nature lovers and fitness enthusiasts.',
    isJoined: false,
    isFree: true,
    points: 10,
  },
  {
    id: 'a3',
    title: 'Book Club',
    category: 'Education',
    date: 'Sep 2 · 3:00 PM',
    location: 'City Library',
    city: 'San Francisco',
    attendees: 8,
    capacity: 15,
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&q=80',
    host: { name: 'Priya Sharma', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya' },
    tags: ['Books', 'Literature', 'Discussion'],
    description: 'Monthly book club discussing "The Alchemist" by Paulo Coelho. New members are always welcome!',
    isJoined: false,
    isFree: true,
    points: 10,
  },
  {
    id: 'a4',
    title: 'Photography Walk',
    category: 'Art',
    date: 'Mon, Nov 7 · 5:00 PM',
    location: 'Embarcadero',
    city: 'San Francisco',
    attendees: 16,
    capacity: 25,
    image: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=400&q=80',
    host: { name: 'Priya Sharma', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya' },
    tags: ['Photography', 'Art', 'Outdoor'],
    description: 'Capture the beauty of San Francisco with fellow photographers. All camera types welcome — DSLR, mirrorless, or mobile!',
    isJoined: false,
    isFree: true,
    points: 10,
  },
  {
    id: 'a5',
    title: 'Startup Meetup',
    category: 'Business',
    date: 'Mon, Nov 7 · 6:30 PM',
    location: 'WeWork SoMa',
    city: 'San Francisco',
    attendees: 21,
    capacity: 40,
    image: 'https://images.unsplash.com/photo-1556761175-4b46a572b786?w=400&q=80',
    host: { name: 'Alex Morgan', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex' },
    tags: ['Startup', 'Networking', 'Business'],
    description: 'Monthly gathering for founders, investors, and startup enthusiasts. Great for networking and sharing ideas.',
    isJoined: false,
    isFree: false,
    price: 5,
    points: 15,
  },
  {
    id: 'a6',
    title: 'English Conversation Club',
    category: 'Language',
    date: 'Mon, Aug 25 · 4:30 PM',
    location: 'Café Lingua',
    city: 'New York',
    attendees: 14,
    capacity: 20,
    image: 'https://images.unsplash.com/photo-1543269865-cbf427effbad?w=400&q=80',
    host: { name: 'James Lee', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James' },
    tags: ['Language', 'Social', 'Learning'],
    description: 'Improve your conversational English in a fun, relaxed setting. Perfect for ESL learners.',
    isJoined: false,
    isFree: true,
    points: 10,
  },
  {
    id: 'a7',
    title: 'Weekend Hike',
    category: 'Outdoors',
    date: 'Sun, Nov 2 · 8:00 AM',
    location: 'Mount Tamalpais',
    city: 'Marin County',
    attendees: 26,
    capacity: 30,
    image: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=400&q=80',
    host: { name: 'Sarah Johnson', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah' },
    tags: ['Hiking', 'Outdoors', 'Fitness'],
    description: 'A scenic 8-mile hike with stunning views of the bay. Moderate difficulty level. Bring water and snacks!',
    isJoined: true,
    isFree: true,
    points: 10,
  },
];

export const mockPeople = [
  {
    id: 'p1',
    name: 'Alex Morgan',
    username: 'alexm',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
    role: 'Photographer',
    location: 'San Francisco',
    interests: ['Photography', 'Travel', 'Coffee'],
    mutualInterests: 3,
    isConnected: false,
  },
  {
    id: 'p2',
    name: 'James Lee',
    username: 'jameslee',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
    role: 'Designer',
    location: 'San Francisco',
    interests: ['UI Design', 'Music', 'Hiking'],
    mutualInterests: 2,
    isConnected: true,
  },
  {
    id: 'p3',
    name: 'Priya Sharma',
    username: 'priyashm',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya',
    role: 'Developer',
    location: 'San Francisco',
    interests: ['Coding', 'Books', 'Yoga'],
    mutualInterests: 4,
    isConnected: false,
  },
  {
    id: 'p4',
    name: 'Marcus Chen',
    username: 'marcusc',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus',
    role: 'Entrepreneur',
    location: 'San Francisco',
    interests: ['Startups', 'Running', 'Chess'],
    mutualInterests: 1,
    isConnected: false,
  },
  {
    id: 'p5',
    name: 'Emma Wilson',
    username: 'emmaw',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
    role: 'Artist',
    location: 'Oakland',
    interests: ['Painting', 'Music', 'Cooking'],
    mutualInterests: 3,
    isConnected: false,
  },
  {
    id: 'p6',
    name: 'David Kim',
    username: 'davidk',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
    role: 'Data Scientist',
    location: 'San Francisco',
    interests: ['Machine Learning', 'Cycling', 'Chess'],
    mutualInterests: 2,
    isConnected: false,
  },
];

export const mockMessages = [
  {
    id: 'm1',
    user: { id: 'p1', name: 'Alex Morgan', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex' },
    lastMessage: 'See you at the guitar session tonight! 🎸',
    time: '2m ago',
    unread: 2,
    online: true,
  },
  {
    id: 'm2',
    user: { id: 'p2', name: 'James Lee', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James' },
    lastMessage: 'That hike was amazing, we should do it again',
    time: '1h ago',
    unread: 0,
    online: true,
  },
  {
    id: 'm3',
    user: { id: 'p3', name: 'Priya Sharma', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya' },
    lastMessage: 'Just finished the book you recommended 📖',
    time: '3h ago',
    unread: 1,
    online: false,
  },
  {
    id: 'm4',
    user: { id: 'p4', name: 'Marcus Chen', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus' },
    lastMessage: 'Are you joining the startup meetup?',
    time: 'Yesterday',
    unread: 0,
    online: false,
  },
];

export const mockConversation = [
  { id: 'c1', senderId: 'p1', text: 'Hey Sarah! Are you coming to the guitar session tonight? 🎸', time: '5:30 PM' },
  { id: 'c2', senderId: 'u1', text: 'Yes! Really excited for it. What time does it start again?', time: '5:32 PM' },
  { id: 'c3', senderId: 'p1', text: 'It starts at 6 PM. The venue is on Market Street', time: '5:33 PM' },
  { id: 'c4', senderId: 'p1', text: 'I can pick you up if you want! I pass by your area', time: '5:34 PM' },
  { id: 'c5', senderId: 'u1', text: 'That would be so helpful! Thank you Alex 😊', time: '5:35 PM' },
  { id: 'c6', senderId: 'p1', text: 'Great! See you at the guitar session tonight! 🎸', time: '5:45 PM' },
];

export const mockNotifications = [
  {
    id: 'n1',
    type: 'activity',
    title: 'Activity Reminder',
    message: 'Guitar Jam Session starts in 2 hours!',
    time: '2h ago',
    read: false,
    icon: '🎸',
  },
  {
    id: 'n2',
    type: 'connection',
    title: 'New Connection',
    message: 'Alex Morgan accepted your connection request',
    time: '3h ago',
    read: false,
    icon: '👋',
  },
  {
    id: 'n3',
    type: 'recommendation',
    title: 'Activity for You',
    message: 'New activity: Photography Walk matches your interests',
    time: '5h ago',
    read: true,
    icon: '📸',
  },
  {
    id: 'n4',
    type: 'activity',
    title: 'Activity Update',
    message: 'Weekend Hike: Capacity almost full! 26/30 spots taken.',
    time: '1d ago',
    read: true,
    icon: '🏔️',
  },
  {
    id: 'n5',
    type: 'message',
    title: 'New Message',
    message: 'Priya Sharma sent you a message',
    time: '1d ago',
    read: true,
    icon: '💬',
  },
];

export const mockCities = ['San Francisco', 'New York', 'Los Angeles', 'Chicago', 'Austin', 'Seattle', 'Boston', 'Denver'];

export const mockCategories = ['All', 'Music', 'Outdoors', 'Art', 'Education', 'Business', 'Language', 'Sports', 'Food', 'Technology', 'Wellness'];

export const mockStats = {
  activitiesJoined: 12,
  connections: 48,
  activitiesCreated: 3,
  streak: 7,
};
